export const CHAT_THEME = {
  CHAT_BACKGROUND: "black",
  TABLE_HEADINGS_COLOR: "#B3A3FA",
  TABLE_FONT_COLOR: "white",
  FONT_COLOR: "#B3A3FA",
  BORDER_COLOR: "#B3A3FA",
  SIDE_MENU_BORDER_COLOR: "#B3A3FA1A",
  SIDE_MENU_BACKGROUND_COLOR: "#191A1F96",
  CHAT_MESSAGE_COLOR: "#C8C8C8",
  USER_ICON_BACKGROUND_COLOR: "#A19ABD",
  USER_ICON_FONT_COLOR: "#231365",
  BUTTON_BACKGROUND_COLOR: "#6846F6",
  INPUT_FIELD_BACKGROUND_COLOR: "#2d2d3a",
};
